### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Suim67** [WGOS/RegionTitle#1]
We tried everything with RedProtect 7.7.2-b357 and sponge 7.3.0 but your flags dont appear. 

Did anyone managed to make this mod work ?

**Comment by wgos** [comment]
Actually, it wasn't working because of some flags were resetting after reload. Developer of RedProtect accepted [my PR](https://github.com/FabioZumbi12/RedProtect/pull/717) with fix.  
But I remember flags were configurable.  
As it could be seen on RedProtect's [Jenkins](http://host.areaz12server.net.br:8081/job/RedProtect/357/) your build was released almost 9 months ago, but my PR was accepted only 2 months ago.  
So you may consider to update to last version of RedProtect or switching to GriefDefender that is more stable and well-build IMHO.  
Remember to backup

**Comment by Suim67** [comment]
Oh damn its working with the RedProtect 7.7.2-b396 thanks a lot ! 

On spongeforge the latest version was 7.7.2-b357 >< and i didnt find that one ... 

Thanks a lot for your help!

**Comment by wgos** [comment]
No problem. Remember that plugin is not tested on RedProtect so there may be more bugs
